name: craft_launcher_modded
description: "A Dart package for launching Minecraft Java Edition with mod loaders such as Fabric. This library extends the `craft_launcher_core` package to provide additional functionality for modded Minecraft instances."
version: 0.0.1
homepage: https://www.karasu256.com

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  mcid_connect: ^0.0.4
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0
  path: ^1.9.1
  http: ^1.4.0
  archive: 4.0.7
  crypto: ^3.0.6
  craft_launcher_core: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
